---
driver:
  name: vagrant

provisioner:
  name: shell

platforms:
  - name: bionic-nginx64
    driver:
      box: bionic-nginx64
      provider: virtualbox

verifier:
  name: inspec

suites:
  - name: default